name:                shared-types
version:             0.1.0.0
github:              "plow-technologies/ocaml-export"
license:             BSD3
author:              "James M.C. Haver II"
maintainer:          "james.haver@plowtech.net"
copyright:           "2019 Plow Technologies"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/ocaml-export/shared-types#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- http-api-data
- servant
- text
- time

library:
  source-dirs: src

tests:
  shared-types-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shared-types
